---
abstract: 'Plack middleware to identify bots and spiders'
author:
  - 'chromatic <chromatic@wgz.org>'
build_requires:
  HTTP::Message::PSGI: 0
  HTTP::Request::Common: 0
  Plack::Builder: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-BotDetector
requires:
  Plack::Middleware: 0
  Plack::Util::Accessor: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/chromatic/Plack-Middleware-BotDetector/issues
  repository: git://github.com/chromatic/Plack-Middleware-BotDetector.git
version: 1.20120920.0752
